version: '3'

services:

  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
     - ./db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "pgsdb"

    ports:
      - "127.0.0.1:3307:3306"

  test_db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "test_pgsdb"
    volumes:
      - ./testdb:/var/lib/mysql

    ports:
      - "127.0.0.1:3308:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:mysql
    ports:
      - "127.0.0.1:8181:80"
    environment:
       - PMA_ARBITRARY=1
       - PMA_HOST=mysql
       - PMA_USER=root
       - PMA_PASSWORD=root
    volumes:
      - "./phpmyadmin/sessions:/sessions"


  web:
    build: .
    command: >
      bash -c "python3 manage.py makemigrations
      && python3 manage.py migrate
      && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "192.168.0.12:8001:8000"
    depends_on:
      - db
      - test_db
